# 📘 NumPy Basics — Foundations, Memory Model, and Array Properties

**Student:** Saee Mane  
**Course/Project:** Python_DataAnalysis_Fundamentals / NUMPY  
**File:** 01_numpy_basics  
**Level:** Beginner → Advanced  
**Status:** Self-Study & Practice Notes  
**Focus:** Core concepts, memory model, and array-based computation  

---

## 1. Introduction & Motivation

### What is NumPy?
NumPy (Numerical Python) is a fundamental Python library for numerical computing. It provides an efficient **multi-dimensional array object (`ndarray`)** and a collection of functions to perform fast mathematical operations on large datasets.

---

### Why was NumPy created?
Python’s built-in lists are flexible but inefficient for numerical calculations. NumPy was designed to enable:

- **Faster computations** using optimized C-based operations  
- **Efficient memory usage** through contiguous storage  
- **Easy handling of large numerical datasets**

---

### Why is NumPy fundamental?
NumPy enables **vectorized operations** and efficient **array-based computation**, which form the foundation of scientific computing, machine learning, and data analysis in Python.

---

### Role of NumPy in the Data Ecosystem
NumPy acts as the **core numerical layer** in Python’s data ecosystem. Many major libraries rely on NumPy arrays for storing and processing data efficiently, including:

- Pandas (data analysis)  
- Matplotlib & Seaborn (visualization)  
- SciPy (scientific computing)  
- Scikit-learn (machine learning)  

---

## 2. NumPy vs Python Lists

### Python Lists
- Can store **mixed data types**  
- Flexible and dynamic in size  
- **Slower** for numerical operations  
- Higher memory overhead  

---

### NumPy Arrays
- Store elements of the **same data type**  
- Use **contiguous memory blocks**  
- Support **fast, vectorized operations**  
- Lower memory overhead  

---

### Performance & Memory Intuition
NumPy arrays are faster and more memory-efficient because:
- Data is stored **contiguously in memory**
- Operations are executed at a **low-level (C/Fortran)** rather than Python loops
- This reduces interpretation overhead and improves CPU cache usage

---

### When Python Lists Are Useful
Use Python lists when working with:
- **Small datasets**
- **Non-numerical or mixed-type data**
- Highly dynamic or nested data structures

---

## 🔎 Learning Outcomes

By the end of this study module, I should be able to:
- Explain why NumPy is faster than Python lists
- Understand how memory layout affects performance
- Identify when to use arrays vs lists in real-world applications
- Describe the role of NumPy in the Python data ecosystem

---

## 📌 Personal Notes

This section is part of my **self-study journey in data analysis and machine learning fundamentals**.  
The goal is to build **strong intuition about performance, memory, and correctness**, not just learn syntax.

---

**Maintained by:** Saee Mane  
**Repository:** Python_DataAnalysis_Fundamentals  


In [1]:
import numpy as np


NumPy vs Python Lists

Creating NumPy Arrays (Basics Only)

NumPy arrays are created using the np.array() function. This converts a Python list (or list of lists) into an ndarray, which supports fast numerical operations.


Python_list

In [2]:
py_list = [1, 2, 3, 4]
py_list

[1, 2, 3, 4]

NumPy array

In [3]:
np_array = np.array([1, 2, 3, 4])
np_array


array([1, 2, 3, 4])

An ndarray is NumPy’s main data structure for storing numbers efficiently.

Stores same data type elements

Can be 1D, 2D, or multi-dimensional

Organized like a grid of values

Dimensions:

1D → Vector

2D → Matrix

3D+ → Tensor

Shape = size of each dimension
Axes = directions along which operations happen

In [4]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
a
b


array([[1, 2],
       [3, 4]])

In [5]:
type(a)

numpy.ndarray

4. Array Properties (Core Attributes)

Every NumPy array has important attributes that describe its structure and memory usage.

dtype – data type of elements stored in the array

ndim – number of dimensions

shape – size of the array along each dimension

size – total number of elements

itemsize – memory size (in bytes) of one element

nbytes – total memory consumed by the array

These attributes help understand how data is stored and how much memory it occupies.

In [6]:
a.dtype

dtype('int64')

In [7]:
a.ndim

1

In [8]:
a.shape

(3,)

In [9]:
a.size

3

In [10]:
a.itemsize

8

In [11]:
a.nbytes

24

In [12]:
np.array([1,2,3] , dtype = np.float32)


array([1., 2., 3.], dtype=float32)

In [13]:
np.array([1,2,3] , dtype = np.int64)

array([1, 2, 3])

In [14]:
a.dtype

dtype('int64')

Type Casting

Type casting means changing the data type of an existing NumPy array.

In [15]:
c = np.array([1,2,3,4] , dtype = np.float32)
c

array([1., 2., 3., 4.], dtype=float32)

In [16]:
a.astype(float)

array([1., 2., 3.])

In [17]:
a.astype(np.int64)

array([1, 2, 3])

NumPy Memory Model

NumPy stores array data in continuous blocks of memory, which makes operations fast and efficient.

In [18]:
a.nbytes


24

Copy vs View

In [19]:
b = a[1:]
c= a.copy()

In [20]:
b.base

array([1, 2, 3])

In [21]:
c.base

Mutability & In-place Operations

NumPy arrays are mutable, meaning their values can be changed after creation.

In [22]:
a[0] = 100


In [23]:
a += 1

In [24]:
b = a + 1

In [25]:
a

array([101,   3,   4])

In [26]:
b

array([102,   4,   5])