In [1]:
import numpy as np
import time
import sys

In [2]:
a  = [1 , 2, 3 ,4 ,5] * 1000000
start  = time.time()
for i in range(len(a)):
    a[i]  = a[i]*2
print("\nTime Taken for list:" , time.time()- start)


Time Taken for list: 0.5151078701019287


In [3]:
a  = [1 , 2, 3 ,4 ,5] * 1000000
start  = time.time()
b = np.array(a)
B = b*2
print("\nTime taken for Numpy array:" ,time.time() - start)


Time taken for Numpy array: 0.2687382698059082


In [4]:
a  = [1 , 2, 3 ,4 ,5]
arr = np.array(a)

print("List Size:" , sys.getsizeof(a))
print("Array Size:" , arr.nbytes)

List Size: 104
Array Size: 40


In [5]:
matrix = [[1, 2, 3] , [4,5,6] , [7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
my_arr = np.array(matrix)
my_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#Check dimesnions in the array or array properties , based on the no of brackets
arr.ndim

1

In [9]:
p = np.array([[[]]])
p.ndim


3

In [10]:
p.shape

(1, 1, 0)

In [11]:
#np.arrange() is used for diplaying the elements within the range directly without any for loop unlike list
range  = np.arange(1 , 10 , 2) #start   , stop , step
range

array([1, 3, 5, 7, 9])

In [12]:
range = np.arange(1 , 100 , 5)
range

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5 , 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2 ,3 , 4 , 5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [16]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [17]:
np.linspace(0  , 10 , 3) #start, stop , no.of values

array([ 0.,  5., 10.])

In [18]:
np.linspace(1 , 10 , 9)

array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
       10.   ])

In [19]:
arr = np.logspace(1 , 3 , 3) #logarithmic scale array -> 10^1 to 10^3.....3 Points
arr

array([  10.,  100., 1000.])

In [20]:
arr = np.logspace(1 , 4 , 5)
arr

array([   10.        ,    56.23413252,   316.22776602,  1778.27941004,
       10000.        ])

In [21]:
arr = np.full(10 , 2) #array with 10 values of 2
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [22]:
arr = np.full([2,4], 7) #2 rows and 4 columns of value 7
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [23]:
#uninitialzed array
c = np.empty
c

<function numpy.empty>

In [24]:
c = np.empty([2 , 3])
c

array([[6.23042070e-307, 4.67297013e-307, 1.69121096e-306],
       [4.67293691e-307, 9.34600962e-307, 1.66880539e-308]])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
arr = np.random.rand(3)
arr

array([0.45932001, 0.06936743, 0.2319857 ])

In [27]:
arr = np.random.rand(5,6)
arr

array([[0.50797396, 0.80784745, 0.606114  , 0.98218275, 0.59413987,
        0.1540045 ],
       [0.19939763, 0.66624083, 0.86475834, 0.76777526, 0.2973732 ,
        0.53370866],
       [0.90003209, 0.27076906, 0.59802703, 0.74754783, 0.0696896 ,
        0.20876083],
       [0.99625907, 0.55608393, 0.44539011, 0.86806812, 0.73013848,
        0.4616829 ],
       [0.95134842, 0.42822505, 0.31203934, 0.96334539, 0.87442398,
        0.83208695]])

In [28]:
np.random.randn(5)

array([-0.90762521, -0.79969986, -0.139461  , -1.28972371,  1.05276479])

In [29]:
np.random.randn(4,5)

array([[ 0.32813094, -0.52207517,  1.1587939 ,  0.73213274, -0.37800755],
       [ 0.40447136,  0.0495919 , -2.3834081 , -1.0858682 , -2.04655035],
       [-1.14518554, -0.36961694, -0.08282368, -0.68736026, -0.05856441],
       [-1.09020605, -2.36512316, -0.02208608,  1.06029768, -0.75194359]])

In [30]:
np.random.randint(1, 100)

5

In [31]:
arr = np.random.randint(1 , 100 , size = (2,3))
arr

array([[46, 42, 62],
       [63, 63, 93]], dtype=int32)

In [32]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
arr.shape

(15,)

In [34]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [35]:
arr.max()

np.int64(14)

In [36]:
arr.min()

np.int64(0)

In [37]:
arr.argmax()

np.int64(14)

In [38]:
arr.argmin()

np.int64(0)

In [39]:
arr.dtype

dtype('int64')