## 🔢 Arithmetic Operations on NumPy Arrays

NumPy allows performing **element-wise arithmetic operations** directly on arrays without using loops. This is known as **vectorization**, and it makes computations both **faster and cleaner**.

---

### 1. Element-wise Operations

Operations are applied to **each corresponding element** in the array.

#### Example
```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # Addition
print(a - b)   # Subtraction
print(a * b)   # Multiplication
print(a / b)   # Division


In [2]:
import numpy as np

###  Operations with Scalars

A single number can be applied to **every element** in the array. This allows you to perform quick transformations without using loops.

In [3]:
a = np.array([1, 2, 3])

print(a + 2)   # Add 2 to each element
print(a * 3)   # Multiply each element by 3


[3 4 5]
[3 6 9]


### Operations with Scalars

A single number can be applied to **every element** in the array. This allows you to perform quick transformations without using loops.

In [4]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)


[[11 22 33]
 [14 25 36]]


## Comparison Operations

These return boolean arrays based on conditions.

In [5]:
a = np.array([1, 2, 3, 4])

print(a > 2)
print(a == 3)


[False False  True  True]
[False False  True False]


## Aggregation Operations

These compute a single value from the entire array.

In [7]:
a = np.array([1, 2, 3, 4])

print(a.sum())
print(a.mean())
print(a.max())
print(a.min())
print(a.argmax())
print(a.argmin())

10
2.5
4
1
3
0


## Universal Functions

In [8]:
arr = np.array([1,4,9,16])
print(np.sqrt(arr))

[1. 2. 3. 4.]


## Exponential Function -> np.exp e^x , x is an integer