## 🔢 Arithmetic Operations on NumPy Arrays

NumPy allows performing **element-wise arithmetic operations** directly on arrays without using loops. This is known as **vectorization**, and it makes computations both **faster and cleaner**.

---

### 1. Element-wise Operations

Operations are applied to **each corresponding element** in the array.

#### Example
```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # Addition
print(a - b)   # Subtraction
print(a * b)   # Multiplication
print(a / b)   # Division


In [2]:
import numpy as np

###  Operations with Scalars

A single number can be applied to **every element** in the array. This allows you to perform quick transformations without using loops.

In [3]:
a = np.array([1, 2, 3])

print(a + 2)   # Add 2 to each element
print(a * 3)   # Multiply each element by 3


[3 4 5]
[3 6 9]


### Operations with Scalars

A single number can be applied to **every element** in the array. This allows you to perform quick transformations without using loops.

In [4]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)


[[11 22 33]
 [14 25 36]]


## Comparison Operations

These return boolean arrays based on conditions.

In [5]:
a = np.array([1, 2, 3, 4])

print(a > 2)
print(a == 3)


[False False  True  True]
[False False  True False]


## Aggregation Operations

These compute a single value from the entire array.

In [7]:
a = np.array([1, 2, 3, 4])

print(a.sum())
print(a.mean())
print(a.max())
print(a.min())
print(a.argmax())
print(a.argmin())

10
2.5
4
1
3
0


## Universal Functions

In [8]:
arr = np.array([1,4,9,16])
print(np.sqrt(arr))

[1. 2. 3. 4.]


## Exponential Function -> ```np.exp e^x , x is an integer```

In [9]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [10]:
print(np.exp(4))

54.598150033144236



```
sine function -> np.sin 
cos function -> np.cos
log function -> np.log
```

In [11]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332])

In [12]:
np.cos(arr)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948])

In [13]:
np.log(arr)

array([0.        , 1.38629436, 2.19722458, 2.77258872])

Standard Deviation

In [14]:
np.std(arr)

np.float64(5.678908345800274)

Get the sum of all the columns in array

In [17]:
a.sum(axis = 0)

np.int64(10)

## Indexing and Slicing of the array

In [32]:
a = [1 , 2, 3 , 4 ,5]
a[-1:-4:- 1]

[5, 4, 3]

In [ ]:
a[: : 2] #returns indexex 0 , 2 , 4

[1, 3, 5]

In [36]:
matrix  =  np.array([[1, 2,3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [38]:
print(matrix[0:2 , 0:3])  #here in [0:2] - 1st row to second , 3rd row not included , and [0:3] is for columns 

[[1 2 3]
 [4 5 6]]


In [39]:
print(matrix[1:, 1:])

[[5 6]
 [8 9]]


## Indexing and Slicing with take()

In [46]:
arr  = np.array([10 , 20 , 30 , 40 , 50 , 60])
ind = [3 , 5] #3 is index of arr directly from arr and 5 is from variable ind
print(np.take(arr , ind))

[40 60]


## Iterating with nditer() - for looping throughout the array, regardless of its shape

In [48]:
arr = np.array([[1,2] , [3,4]])

In [49]:
for x in np.nditer(arr):
    print(x , end = " ")

1 2 3 4 

In [53]:
A = np.arange(0,10)
A.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
for y in np.nditer(A):
    print(y , end = " ")

0 1 2 3 4 5 6 7 8 9 

## ```ndenumerate```  - we can get both index + value at that index position

In [56]:
for ind,x in np.ndenumerate(arr):
    print(ind , x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


## View vs Copy

In [62]:
#View - orginal array affected
arr  = np.array([1,2,3,4,5,6])
view = arr[1:5]

In [64]:
view[0] = 200

In [65]:
view

array([200,   3,   4,   5])

In [66]:
arr

array([  1, 200,   3,   4,   5,   6])

In [68]:
#Copy - Original array unchnages , new has the changes
copy = arr[1:5]
copy[2] = 4

In [69]:
copy

array([200,   3,   4,   5])

In [70]:
arr

array([  1, 200,   3,   4,   5,   6])

## ```transpose()``` - Transpose of a Matrix

In [4]:
arr = np.array([[1,2 ,3], [4 ,5 ,6] , [7 , 8, 9]])
print(arr.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


## ```Swapaxes``` - swap 2 specific axes in the matrix

In [78]:
swap = np.swapaxes(arr , 0 , 1) # means that i want to swap 0 the axis with the 1st axis
swap.shape

(3, 3)

concatenation

In [ ]:
a = [1 , 2, 3]
b = [10 , 20 , 30]
result = np.concatenate((a,b))
result

array([[ 1,  2,  3],
       [10, 20, 30]])

In [82]:
result.reshape(2,3)

array([[ 1,  2,  3],
       [10, 20, 30]])

## ```vstack()``` -Vertical stack means putting arrays on top of each other.
Like stacking books one above another.

In [89]:
arr1 = np.vstack((a , b))
arr

array([[ 1,  2,  3],
       [10, 20, 30]])

## ```hstack()``` - Horizontal stack means putting arrays side by side.
Like placing books next to each other on a shelf.

In [90]:
print(np.hstack((a,b)))

[ 1  2  3 10 20 30]


In [ ]:
# One more method - axis-> 0 is row wise , axis->1 is column wise
print(np.stack((a, b), axis = 0)) # arrays will be joined columns wise , replacement for hstack()

[[ 1  2  3]
 [10 20 30]]


In [93]:
# One more method - axis-> 0 is row wise , axis->1 is column wise
print(np.stack((a, b), axis = 1)) # arrays will be joined columns wise , replacement for vstack

[[ 1 10]
 [ 2 20]
 [ 3 30]]


## Splitting the array

In [95]:
print(np.split(arr , 2))

[array([[1, 2, 3]]), array([[10, 20, 30]])]


In [115]:
# Horizontally split - cuts sideways (left to right)
print(np.hsplit(arr , 3)) #Cut this array into 3 equal parts.

[array([[ 1],
       [10]]), array([[ 2],
       [20]]), array([[ 3],
       [30]])]


In [124]:
#Take array a and divide it into 2 pieces vertically (by rows)  
print(np.vsplit(arr , 2))

[array([[1, 2, 3]]), array([[10, 20, 30]])]


## ```repeat()``` - repeat() means “copy this value multiple times.”
It takes each element in an array and repeats it as many times as you ask.

In [100]:
print(np.repeat(arr , 2))

[ 1  1  2  2  3  3 10 10 20 20 30 30]


## ```tile``` - repeats the whole array in the no of times entered

In [125]:
print(np.tile(arr , 2))

[[ 1  2  3  1  2  3]
 [10 20 30 10 20 30]]


## Aggreagate Functions - Aggregate functions take many values and give you a summary.
Think: total, average, biggest, smallest, spread.

In [ ]:
np.sum(a)

np.float64(0.816496580927726)

In [103]:
np.min(a)


np.int64(1)

In [104]:
np.max(a)


np.int64(3)

In [105]:
np.argmin(a)


np.int64(0)

In [106]:
np.argmax(a)


np.int64(2)

In [110]:
# Variance of A(spread , squared from of std) --> Variance tells you how spread out your numbers are.Are the numbers close together or far apart?
np.var(a) 

np.float64(0.6666666666666666)

In [108]:
np.std(a)

np.float64(0.816496580927726)

In [127]:
np.mean(a)

np.float64(2.0)

In [128]:
np.median(a)

np.float64(2.0)

In [130]:
arr

array([[ 1,  2,  3],
       [10, 20, 30]])

In [131]:
print(np.sum(arr , axis = 0))

[11 22 33]


In [132]:
print(np.sum(arr , axis = 1))

[ 6 60]


 🔁 Cumulative Operations (NumPy)

**Cumulative means “running result.”**  
Instead of giving one final answer, cumulative operations show the **step-by-step result** as you move through the array.

---

Example Array
```[1, 2, 3, 4]```

Normal Sum (Final Answer)
```1 + 2 + 3 + 4 = 10```

Cumulative Sum (Step-by-Step)
```
[1,
1+2,
1+2+3,
1+2+3+4]
```

Result:
```[1, 3, 6, 10]```


```cumsum()``` - cummulative sum 

In [133]:
print(np.cumsum(a))

[1 3 6]


## ```cumprod()``` - calculates product step by step

In [135]:
print(np.cumprod(a)) # 1x1 = 1 , 1x2 = 2 , 1x2x3 = 6

[1 2 6]


## Conditional Based choices

## ```np.where()```
`np.where()` is used to **find or replace values based on a condition**.  
Think of it like:

> **“If this condition is true, do this. Otherwise, do that.”**

In [5]:
result = np.where(arr<2 , "Low" , "High")
result

array([['Low', 'High', 'High'],
       ['High', 'High', 'High'],
       ['High', 'High', 'High']], dtype='<U4')

## `argwhere()` - used to find exact positions in the array where the conditions are **true**

In [6]:
print(np.argwhere(arr>3))

[[1 0]
 [1 1]
 [1 2]
 [2 0]
 [2 1]
 [2 2]]


In [12]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## `np.logical_and()` - Returns true only if both the conditions are True for an element


In [9]:
mask = np.logical_and(arr>3 , arr<2) 
mask

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

## `np.logical_or()` - is used to **combine two conditions** and returns `True` if **at least one condition is true** for each element.

In [17]:
mask = np.logical_or(arr>3 , arr<2)
mask

array([[ True, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [19]:
arr[mask]

array([1, 1, 1, 1, 1, 1, 1])

## ``np.nonzero()`` - Fetches indexes where the elements are non-zero

In [20]:
print(np.nonzero(arr))

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))


## Broadcasting - automatically stretch the smaller array to match the size of the larger array so that we can perform operations on both the arrays.
## Rules:
    `1. If shapes are equal  they're compatible directly , no need of trasnformation`
    `2. If one is 1, it can be stretched to match the other`
    `3. Error if shapes are not equal - Error`


In [ ]:
a = np.array([[1,2,3]])

b = np.array([[5,6 ,7], [1,2,3]])
print(a+b)

[[ 6  8 10]
 [ 2  4  6]]


In [ ]:
a = np.array([[1,2,3]])

b = np.array([5,6])
print(a+b)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[39], line 4
      1 a = np.array([[1,2,3]])
      3 b = np.array([5,6])
----> 4 print(a+b)

ValueError: operands could not be broadcast together with shapes (1,3) (2,) 

## `Vectorization`
 - In NumPy, vectorization means using NumPy’s built-in array operations instead of Python loops so the work runs in fast, low-level code (C), not slow Python.

## `np.vectorize()` - convert a regular function to be applied on an array

In [41]:
def square(x):
    return x*x
    
vfunc = np.vectorize(square)
print(vfunc(arr))

[[1 4 9]
 [1 1 1]
 [1 1 1]]


In [42]:
arr

array([[1, 2, 3],
       [1, 1, 1],
       [1, 1, 1]])

## Dealing with missing values - null values

## `np.nan` -> not a number

In [55]:
a = np.array([1.0 , 2.0 , 3.0 , np.nan , 5.0 ,6.0])
a

array([ 1.,  2.,  3., nan,  5.,  6.])

## `np.inf` and `-np.inf` -> positive and negative infintes

In [57]:
print(np.isnan(a))


[False False False  True False False]


In [69]:
b = np.array([1 , 3, np.nan , np.inf , 10, 40])
b

array([ 1.,  3., nan, inf, 10., 40.])

In [70]:
print(np.isinf(b))

[False False False  True False False]


In [ ]:
print(np.isfinite(b)) # Removes nan and inf

[ True  True False False  True  True]


## Replacing or removing these values

In [80]:
new = np.nan_to_num(b)
new

array([1.00000000e+000, 3.00000000e+000, 0.00000000e+000, 1.79769313e+308,
       1.00000000e+001, 4.00000000e+001])

In [ ]:
print(np.nanmean(b))  #1 + 3 + inf + 10 + 40 = inf ; inf/5  = inf


inf


In [ ]:
print(np.nansum(b))  #1 + 3 + inf + 10 + 40 = inf

inf


In [ ]:
clean = b[np.isfinite(b)]  # Removes nan and inf
print(np.mean(clean))


13.5
