## 🔢 Arithmetic Operations on NumPy Arrays

NumPy allows performing **element-wise arithmetic operations** directly on arrays without using loops. This is known as **vectorization**, and it makes computations both **faster and cleaner**.

---

### 1. Element-wise Operations

Operations are applied to **each corresponding element** in the array.

#### Example
```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # Addition
print(a - b)   # Subtraction
print(a * b)   # Multiplication
print(a / b)   # Division


In [2]:
import numpy as np

###  Operations with Scalars

A single number can be applied to **every element** in the array. This allows you to perform quick transformations without using loops.

In [3]:
a = np.array([1, 2, 3])

print(a + 2)   # Add 2 to each element
print(a * 3)   # Multiply each element by 3


[3 4 5]
[3 6 9]


### Operations with Scalars

A single number can be applied to **every element** in the array. This allows you to perform quick transformations without using loops.

In [4]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

print(a + b)


[[11 22 33]
 [14 25 36]]


## Comparison Operations

These return boolean arrays based on conditions.

In [5]:
a = np.array([1, 2, 3, 4])

print(a > 2)
print(a == 3)


[False False  True  True]
[False False  True False]


## Aggregation Operations

These compute a single value from the entire array.

In [7]:
a = np.array([1, 2, 3, 4])

print(a.sum())
print(a.mean())
print(a.max())
print(a.min())
print(a.argmax())
print(a.argmin())

10
2.5
4
1
3
0


## Universal Functions

In [8]:
arr = np.array([1,4,9,16])
print(np.sqrt(arr))

[1. 2. 3. 4.]


## Exponential Function -> ```np.exp e^x , x is an integer```

In [9]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [10]:
print(np.exp(4))

54.598150033144236



```
sine function -> np.sin 
cos function -> np.cos
log function -> np.log
```

In [11]:
np.sin(arr)

array([ 0.84147098, -0.7568025 ,  0.41211849, -0.28790332])

In [12]:
np.cos(arr)

array([ 0.54030231, -0.65364362, -0.91113026, -0.95765948])

In [13]:
np.log(arr)

array([0.        , 1.38629436, 2.19722458, 2.77258872])

Standard Deviation

In [14]:
np.std(arr)

np.float64(5.678908345800274)

Get the sum of all the columns in array

In [17]:
a.sum(axis = 0)

np.int64(10)

## Indexing and Slicing of the array

In [32]:
a = [1 , 2, 3 , 4 ,5]
a[-1:-4:- 1]

[5, 4, 3]

In [ ]:
a[: : 2] #returns indexex 0 , 2 , 4

[1, 3, 5]

In [36]:
matrix  =  np.array([[1, 2,3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [38]:
print(matrix[0:2 , 0:3])  #here in [0:2] - 1st row to second , 3rd row not included , and [0:3] is for columns 

[[1 2 3]
 [4 5 6]]


In [39]:
print(matrix[1:, 1:])

[[5 6]
 [8 9]]


Indexing and Slicing with take()

In [46]:
arr  = np.array([10 , 20 , 30 , 40 , 50 , 60])
ind = [3 , 5] #3 is index of arr directly from arr and 5 is from variable ind
print(np.take(arr , ind))

[40 60]


Iterating with nditer() - for looping throughout the array, regardless of its shape

In [48]:
arr = np.array([[1,2] , [3,4]])

In [49]:
for x in np.nditer(arr):
    print(x , end = " ")

1 2 3 4 

In [53]:
A = np.arange(0,10)
A.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
for y in np.nditer(A):
    print(y , end = " ")

0 1 2 3 4 5 6 7 8 9 

```#ndenumerate```  - we can get both index + value at that index position

In [56]:
for ind,x in np.ndenumerate(arr):
    print(ind , x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


View vs Copy